cols:
  - year
  - mileage_km
  - engine_capacity
  - engine_power
  - mixed_drive_fuel_consumption
  - price_usd
  - brand
  - engine_type
  - transmission_type
  - interior_material
  - body_type
  - drive_type
  - options

min_year: 1978
max_mileage: 600000
