model: cb
model_params:
  estimator_name: cb
  transformer_name: ct
  log_transform: true

  cat_features:
    - brand
    - engine_type
    - transmission_type
    - interior_material
    - body_type
    - drive_type

  num_features:
    - year
    - options 
    - mileage_km 
    - engine_power
    - engine_capacity 
    - mixed_drive_fuel_consumption

metrics:
  - rmse
  - mae
  - r2_score
