model: forest
model_params:
  estimator_name: forest
  transformer_name: ss
  log_transform: false

metrics:
  - rmse
  - mae
  - r2_score

optimizer_params:
  direction: minimize
  n_trials: 50
  optimization_metric: rmse